// import 'babel-polyfill';
// import "./class/lesson1.js";
// import './class/lesson2.js';
// import './class/lesson3.js';
// import './class/lesson4.js';
// import './class/lesson5.js';
// import './class/lesson6.js';
// import './class/lesson7.js';
// import './class/lesson8.js';
// import './class/lesson9.js';
// import './class/lesson10.js';
// import './class/lesson11.js';
// import './class/lesson12.js';
 import './class/lesson13.js';
